export const PUBLIC_ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
};

export const PRIVATE_ROUTES = {
  DASHBOARD: "/dashboard",
  USERS: "/users",
  USERS_LIST: "/users/list",
  USERS_VIEW: "/users/view",
  DASHBOARD_CRM: "/dashboard/crm",
  INVOICES_LIST: "/invoices/list",
  INVOICES_PREVIEW: "/invoices/preview",
  INVOICES_ADD: "/invoices/add",
  INVOICES_EDIT: "/invoices/edit",
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  USERS_VIEW_ACCOUNT: "/users/view/account",
  USERS_VIEW_SECURITY: "/users/view/security",
  USERS_VIEW_BILLING: "/users/view/billing",
  USERS_VIEW_NOTIFICATIONS: "/users/view/notifications",
  USERS_VIEW_CONNECTIONS: "/users/view/connections",
  TRANSACTIONS_LIST: "/transactions/list",
  SUBSCRIPTIONS_LIST: "/subscriptions/list",
  SUBSCRIPTIONS_VIEW: "/subscriptions/view",
  BADGES: "/badges",
  BADGES_LIST: "/badges/list",
  BADGES_ADD: "/badges/add",
  BADGES_EDIT: "/badges/edit",
  COMPANIES: "/companies",
  COMPANIES_LIST: "/companies/list",
  COMPANIES_VIEW: "/companies/view",
  COMPANIES_VIEW_JOBS: "/companies/view/jobs",
  COMPANIES_VIEW_EVENTS: "/companies/view/events",
  COMPANIES_VIEW_BUSINESS: "/companies/view/businessleads",
  COMPANIES_VIEW_HIRING: "/companies/view/hiring",
  COMPANIES_VIEW_ENGAGEMENT: "/companies/view/engagement",
  COMPANIES_VIEW_SPONSORSHIP: "/companies/view/sponsorship",
  COMPANIES_VIEW_BOOST: "/companies/view/boost",
  COMPANIES_VIEW_GROWTH: "/companies/view/companygrowth",
  PROMO_CODES_LIST: "/promo-codes/list",
  EVENTS_LIST: "/events/list",
  GROUPS_LIST: "/groups/list",
  GAME_CONFIGS: "/game-configs",
  GAME_CONFIGS_LIST: "/game-configs/list",
  GAME_CONFIGS_VIEW: "/game-configs/view",
  BETS_HISTORY: "/bets-history",
  BETS_HISTORY_LIST: "/bets-history/list",
  CONFIGS: "/configs",
  CONFIGS_LIST: "/configs/list",
  CHAT: "/chat",
  CHAT_ROOMS_LIST: "/chat/rooms/list",
  CHAT_MESSAGES: "/chat/messages",
  CHAT_LIVE: "/chat/live",

  // Bonus Slides
  BONUS_SLIDES: "/bonus-slides",
  BONUS_SLIDES_LIST: "/bonus-slides/list",
  BONUS_SLIDES_ADD: "/bonus-slides/add",
  BONUS_SLIDES_EDIT: "/bonus-slides/edit",
};
export const ROUTES = {
  ...PUBLIC_ROUTES,
  ...PRIVATE_ROUTES,
};
