export const FIELD_NAMES = {
  NAME: "name",
  FIRST_NAME: "firstName",
  LAST_NAME: "lastName",
  EMAIL: "email",
  PASSWORD: "password",
  NEW_PASSWORD: "newPassword",
  CONFIRM_PASSWORD: "confirmPassword",
  COUNTRY: "country",
  ROLE: "role",
  STATUS: "status",
  CONTACT: "contactNumber",
  COMPANY_NAME: "companyName",
  TAX_ID: "taxId",
  VAT_NUMBER: "vatNumber",
  BILLING_EMAIL: "billingEmail",
  STATE: "state",
  ZIPCODE: "zipcode",
  SECTOR: "sector",
  EMPLOYEE_COUNT: "employeeCount",
  WEBSITE: "website",
  HEADQUARTERS: "headquarters",
  SERVICES: "services",
  MISSION: "mission",
  VISION: "vision",
  CORE_VALUES: "coreValues",
  COMPANY_BIO: "companyBio",
  REVENUE: "revenue",
  TURNOVER: "turnover",
  CONTACT_EMAIL: "contactEmail",
  CONTACT_PHONE: "contactPhone",
  CREATED_DATE: "createdDate",
  LAST_UPDATED: "lastUpdated",
  NOTES: "notes",
} as const;

export const STRING = {
  NAME: "Full Name",
  EMAIL: "Email",
  PASSWORD: "Password",
  NEW_PASSWORD: "New Password",
  CONFIRM_PASSWORD: "Confirm Password",
  COUNTRY: "Country",
  ROLE: "Role",
  STATUS: "Status",
  CONTACT: "Contact",
  COMPANY_NAME: "Company Name",
  TAX_ID: "Tax ID",
  VAT_NUMBER: "VAT Number",
  BILLING_EMAIL: "Billing Email",
  STATE: "State",
  ZIPCODE: "Zipcode",
  DELETE_USER: "Delete User",
  SUSPEND_USER: "Suspend User",
  LOGOUT_USER: "Logout User",
  BLOCK_USER: "Block User",
  UNBLOCK_USER: "Unblock User",
  SECTOR: "Industry & Sector",
  EMPLOYEE_COUNT: "Company Size (Employees)",
  WEBSITE: "Website URL",
  HEADQUARTERS: "Headquarters Location",
  SERVICES: "Services/Tags (max 6)",
  MISSION: "Mission",
  VISION: "Vision",
  CORE_VALUES: "Core Values",
  COMPANY_BIO: "Company Bio",
  REVENUE: "Annual Revenue",
  TURNOVER: "Annual Turnover",
  CONTACT_EMAIL: "Contact Email",
  CONTACT_PHONE: "Contact Phone",
  CREATED_DATE: "Created Date",
  LAST_UPDATED: "Last Updated",
  NOTES: "Admin Notes",
} as const;

export const MESSAGES = {
  DELETE_CONFIRMATION: "Are you sure you want to delete this user?",
  SUSPEND_CONFIRMATION: "Are you sure you want to suspend this user?",
  LOGOUT_CONFIRMATION:
    "Are you sure you want to logout this user? This will end their current session.",
  BLOCK_CONFIRMATION: "Are you sure you want to block this user?",
  UNBLOCK_CONFIRMATION: "Are you sure you want to unblock this user?",
  COMPANY_NAME_REQUIRED: "Company name is required",
  SECTOR_REQUIRED: "Industry sector is required",
  HEADQUARTERS_REQUIRED: "Headquarters location is required",
  EMPLOYEE_COUNT_REQUIRED: "Company size is required",
  EMAIL_REQUIRED: "Email is required",
  CONTACT_REQUIRED: "Contact number is required",
  COUNTRY_REQUIRED: "Country is required",
  INVALID_EMAIL: "Please enter a valid email address",
  INVALID_URL: "Please enter a valid URL starting with http:// or https://",
  MISSION_REQUIRED: "Mission is required",
  VISION_REQUIRED: "Vision is required",
  CORE_VALUES_REQUIRED: "Core values are required",
  COMPANY_BIO_REQUIRED: "Company bio is required",
  MISSION_MAX_LENGTH: "Mission must be less than 250 characters",
  VISION_MAX_LENGTH: "Vision must be less than 250 characters",
  CORE_VALUES_MAX_LENGTH: "Core values must be less than 250 characters",
  COMPANY_BIO_MAX_LENGTH: "Company bio must be less than 500 characters",
  REVENUE_REQUIRED: "Revenue is required",
  TURNOVER_REQUIRED: "Turnover is required",
  CONTACT_EMAIL_REQUIRED: "Contact email is required",
  CONTACT_PHONE_REQUIRED: "Contact phone is required",
  CREATED_DATE_REQUIRED: "Created date is required",
  LAST_UPDATED_REQUIRED: "Last updated date is required",
  NOTES_MAX_LENGTH: "Notes must be less than 1000 characters",
  REMOVE_MEMBER: "Are you sure you want to remove this team member?",
} as const;

export type StringKey = keyof typeof STRING;

export const REGEX = {
  NAME: /^[A-Za-z\s]+$/,
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  STRONG_PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_]).+$/,
  PHONE: /^\+?\d{10,14}$/,
  USERNAME: /\w/,
  URL: /^https?:\/\/.+/,
};
