// Group-specific constants for Groups section

import { ENTITY_STATUS, ENTITY_STATUS_LABELS } from "@/shared/constants";

export const GROUP_STATUS_OPTIONS = [
  {
    label: ENTITY_STATUS_LABELS[ENTITY_STATUS.ACTIVE],
    value: ENTITY_STATUS.ACTIVE,
  },
  {
    label: ENTITY_STATUS_LABELS[ENTITY_STATUS.FLAGGED],
    value: ENTITY_STATUS.FLAGGED,
  },
  {
    label: ENTITY_STATUS_LABELS[ENTITY_STATUS.INACTIVE],
    value: ENTITY_STATUS.INACTIVE,
  },
];

export enum GROUP_TYPE {
  PUBLIC = 1,
  PRIVATE = 2,
  SECRET = 3,
}
export const GROUP_TYPE_LABELS = {
  [GROUP_TYPE.PUBLIC]: "Public",
  [GROUP_TYPE.PRIVATE]: "Private",
  [GROUP_TYPE.SECRET]: "Secret",
};
export const GROUP_TYPE_OPTIONS = [
  { label: GROUP_TYPE_LABELS[GROUP_TYPE.PUBLIC], value: GROUP_TYPE.PUBLIC },
  { label: GROUP_TYPE_LABELS[GROUP_TYPE.PRIVATE], value: GROUP_TYPE.PRIVATE },
  { label: GROUP_TYPE_LABELS[GROUP_TYPE.SECRET], value: GROUP_TYPE.SECRET },
];

export enum GROUP_TRUST_LEVEL {
  LEVEL_1 = 1,
  LEVEL_2 = 2,
  LEVEL_3 = 3,
  LEVEL_4 = 4,
}
export const GROUP_TRUST_LEVEL_LABELS = {
  [GROUP_TRUST_LEVEL.LEVEL_1]: "Level 1",
  [GROUP_TRUST_LEVEL.LEVEL_2]: "Level 2",
  [GROUP_TRUST_LEVEL.LEVEL_3]: "Level 3",
  [GROUP_TRUST_LEVEL.LEVEL_4]: "Level 4",
};
export const GROUP_TRUST_LEVEL_OPTIONS = [
  {
    label: GROUP_TRUST_LEVEL_LABELS[GROUP_TRUST_LEVEL.LEVEL_1],
    value: GROUP_TRUST_LEVEL.LEVEL_1,
  },
  {
    label: GROUP_TRUST_LEVEL_LABELS[GROUP_TRUST_LEVEL.LEVEL_2],
    value: GROUP_TRUST_LEVEL.LEVEL_2,
  },
  {
    label: GROUP_TRUST_LEVEL_LABELS[GROUP_TRUST_LEVEL.LEVEL_3],
    value: GROUP_TRUST_LEVEL.LEVEL_3,
  },
  {
    label: GROUP_TRUST_LEVEL_LABELS[GROUP_TRUST_LEVEL.LEVEL_4],
    value: GROUP_TRUST_LEVEL.LEVEL_4,
  },
];

export enum GROUP_ACTIVITY {
  HIGH = 1,
  LOW = 2,
  DORMANT = 3,
  NO_ACTIVITY = 4,
}
export const GROUP_ACTIVITY_LABELS = {
  [GROUP_ACTIVITY.HIGH]: "Active Recently",
  [GROUP_ACTIVITY.LOW]: "Low Activity",
  [GROUP_ACTIVITY.DORMANT]: "Dormant",
  [GROUP_ACTIVITY.NO_ACTIVITY]: "No Activity",
};
export const GROUP_ACTIVITY_OPTIONS = [
  {
    label: GROUP_ACTIVITY_LABELS[GROUP_ACTIVITY.HIGH],
    value: GROUP_ACTIVITY.HIGH,
  },
  {
    label: GROUP_ACTIVITY_LABELS[GROUP_ACTIVITY.LOW],
    value: GROUP_ACTIVITY.LOW,
  },
  {
    label: GROUP_ACTIVITY_LABELS[GROUP_ACTIVITY.DORMANT],
    value: GROUP_ACTIVITY.DORMANT,
  },
  {
    label: GROUP_ACTIVITY_LABELS[GROUP_ACTIVITY.NO_ACTIVITY],
    value: GROUP_ACTIVITY.NO_ACTIVITY,
  },
];
export enum GROUP_TOPICS_ENUM {
  TECHNOLOGY = 1,
  BUSINESS = 2,
  HEALTH = 3,
  EDUCATION = 4,
  ART = 5,
  SCIENCE = 6,
  SPORTS = 7,
}

export const GROUP_TOPICS_LABELS = {
  [GROUP_TOPICS_ENUM.TECHNOLOGY]: "Technology",
  [GROUP_TOPICS_ENUM.BUSINESS]: "Business",
  [GROUP_TOPICS_ENUM.HEALTH]: "Health",
  [GROUP_TOPICS_ENUM.EDUCATION]: "Education",
  [GROUP_TOPICS_ENUM.ART]: "Art",
  [GROUP_TOPICS_ENUM.SCIENCE]: "Science",
  [GROUP_TOPICS_ENUM.SPORTS]: "Sports",
};

export const GROUP_TOPICS_OPTIONS = [
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.TECHNOLOGY],
    value: GROUP_TOPICS_ENUM.TECHNOLOGY,
  },
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.BUSINESS],
    value: GROUP_TOPICS_ENUM.BUSINESS,
  },
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.HEALTH],
    value: GROUP_TOPICS_ENUM.HEALTH,
  },
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.EDUCATION],
    value: GROUP_TOPICS_ENUM.EDUCATION,
  },
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.ART],
    value: GROUP_TOPICS_ENUM.ART,
  },
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.SCIENCE],
    value: GROUP_TOPICS_ENUM.SCIENCE,
  },
  {
    label: GROUP_TOPICS_LABELS[GROUP_TOPICS_ENUM.SPORTS],
    value: GROUP_TOPICS_ENUM.SPORTS,
  },
];
