export const companies_data = {
  status: "success",
  message: "Companies fetched successfully",
  type: "success",
  statusCode: 200,
  data: {
    companies: [
      {
        _id: "001",
        companyName: "Synapse Tech",
        email: "info@synapsetech.com",
        companyProfilePicture: "/images/companies/synapse.png",
        contactNumber: "+1-234-567-8901",
        country: 1,
        sector: 1,
        isSuspended: false,
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-07-01"),
      },
      {
        _id: "002",
        companyName: "GreenFields Agri",
        email: "contact@greenfields.com",
        companyProfilePicture: "/images/companies/greenfields.png",
        contactNumber: "+44-20-7946-0958",
        country: 1,
        sector: 2,
        isSuspended: false,
      },
      {
        _id: "003",
        companyName: "MediNova Health",
        email: "hello@medinova.org",
        companyProfilePicture: "/images/companies/medinova.png",
        contactNumber: "+1-312-456-7890",
        country: 1,
        sector: 3,
        isSuspended: true,
      },
      {
        _id: "004",
        companyName: "FinCore Solutions",
        email: "support@fincore.io",
        companyProfilePicture: "/images/companies/fincore.png",
        contactNumber: "+61-2-9876-5432",
        country: 1,
        sector: 1,
        isSuspended: false,
      },
      {
        _id: "005",
        companyName: "EcoBuild Constructions",
        email: "build@ecobuild.com",
        companyProfilePicture: "/images/companies/ecobuild.png",
        contactNumber: "+91-9988776655",
        country: 1,
        sector: 4,
        isSuspended: false,
      },
      {
        _id: "006",
        companyName: "NovaLearn",
        email: "admin@novalearn.edu",
        companyProfilePicture: "/images/companies/novalearn.png",
        contactNumber: "+33-1-2345-6789",
        country: 1,
        sector: 1,
        isSuspended: false,
      },
      {
        _id: "007",
        companyName: "AeroCore Systems",
        email: "fly@aerocore.com",
        companyProfilePicture: "/images/companies/aerocore.png",
        contactNumber: "+49-89-1234-5678",
        country: 1,
        sector: 5,
        isSuspended: true,
      },
      {
        _id: "008",
        companyName: "BrightSpark Energy",
        email: "energy@brightspark.net",
        companyProfilePicture: "/images/companies/brightspark.png",
        contactNumber: "+1-415-000-0000",
        country: 1,
        sector: 6,
        isSuspended: false,
      },
      {
        _id: "009",
        companyName: "AquaPure Waters",
        email: "aqua@aquapure.com",
        companyProfilePicture: "/images/companies/aquapure.png",
        contactNumber: "+27-11-234-5678",
        country: 1,
        sector: 7,
        isSuspended: false,
      },
      {
        _id: "010",
        companyName: "SkyNet Logistics",
        email: "logistics@skynet.org",
        companyProfilePicture: "/images/companies/skynet.png",
        contactNumber: "+65-6543-2109",
        country: 1,
        sector: 8,
        isSuspended: false,
      },
    ],
    total: 129,
  },
};
export const sampleCompany = [
  {
    logo: "/avatars/devon.png",
    name: "TechNova Inc.",
    description: "Innovating the future of AI and robotics.",
    industry: "Technology & AI",
  },
  {
    logo: "/avatars/devon.png",
    name: "TechNova Inc.",
    description: "Innovating the future of AI and robotics.",
    industry: "Technology & AI",
  },
];
export const sampleViewers = [
  {
    avatar: "/avatars/devon.png",
    name: "Devon Lane",
    description:
      "Experienced in HTML, CSS, JS, Bootstrap, GSAP, PHP, SQL and WordPress. Specializing in creating responsive, user-friendly web",
    timeViewed: "10 h",
  },
  {
    avatar: "/avatars/guy.png",
    name: "Guy Hawkins",
    description:
      "Experienced in HTML, CSS, JS, Bootstrap, GSAP, PHP, SQL and WordPress. Specializing in creating responsive, user-friendly web",
    timeViewed: "10 h",
  },
  {
    avatar: "/avatars/annette.png",
    name: "Annette Black",
    description:
      "Experienced in HTML, CSS, JS, Bootstrap, GSAP, PHP, SQL and WordPress. Specializing in creating responsive, user-friendly web",
    timeViewed: "10 h",
  },
  {
    avatar: "/avatars/pg.png",
    name: "P&G Company",
    description:
      "Experienced in HTML, CSS, JS, Bootstrap, GSAP, PHP, SQL and WordPress. Specializing in creating responsive, user-friendly web",
    timeViewed: "10 h",
  },
];
